"""Asset ledger and copyright policy.

Every external file the edit may use lives in the assets folder and must have an
entry in assets/ledger.json. Anything without a verifiable, permitted licence is
rejected *before* planning, and QC fails if a rejected asset still reaches the cut.

ledger.json:
{
  "assets": [
    {"file": "quetta_valley.jpg", "tags": ["quetta", "valley", "mountains"],
     "kind": "image", "license": "CC-BY-4.0", "source": "https://...", "author": "Name",
     "ai_generated": false, "depicts": "present"}            # or "historical"
  ]
}
"""
import re
from pathlib import Path

from .media import read_json

# Ordered by preference (matches the sourcing policy in docs/DIRECTING_BRIEF.md)
ALLOWED = {
    "own": "Creator's own footage/asset",
    "ai-generated": "Generated for this channel",
    "generated": "Generated by this pipeline (maps, graphics, music, sfx)",
    "public-domain": "Public domain",
    "CC0": "Creative Commons Zero",
    "CC-BY-4.0": "Creative Commons Attribution 4.0 (credit required)",
    "CC-BY-3.0": "Creative Commons Attribution 3.0 (credit required)",
    "CC-BY-2.0": "Creative Commons Attribution 2.0 (credit required)",
    "CC-BY-SA-4.0": "Creative Commons Attribution-ShareAlike 4.0 (credit required)",
    "CC-BY-SA-3.0": "Creative Commons Attribution-ShareAlike 3.0 (credit required)",
    "gov-permitted": "Government/archive material whose terms permit this use (record the terms URL)",
    "licensed-stock": "Stock with a valid licence (record licence id)",
    "licensed": "Other written licence/permission (record reference)",
}
NEEDS_CREDIT = ("CC-BY",)
NEEDS_REFERENCE = ("gov-permitted", "licensed-stock", "licensed")


def check_entry(a: dict) -> list:
    """Return a list of problems (empty == usable)."""
    lic = (a.get("license") or "").strip()
    problems = []
    if lic not in ALLOWED:
        problems.append(f"licence '{lic or 'missing'}' is not in the allowed list")
    if re.search(r"-(NC|ND)(-|$)", lic.upper()):
        # a monetised channel is commercial use, and an edit is a derivative work
        problems.append("non-commercial / no-derivatives licence")
    if lic not in ("own", "ai-generated", "generated") and not a.get("source"):
        problems.append("no source URL/reference recorded")
    if lic.startswith(NEEDS_CREDIT) and not a.get("author"):
        problems.append("attribution licence but no author recorded")
    if lic in NEEDS_REFERENCE and not a.get("reference"):
        problems.append("licence/terms reference (licence id or terms URL) not recorded")
    if a.get("watermarked"):
        problems.append("watermarked asset")
    return problems


def load_ledger(assets_dir):
    assets_dir = Path(assets_dir) if assets_dir else None
    if not assets_dir or not (assets_dir / "ledger.json").exists():
        return {"usable": [], "rejected": [], "unlisted": []}
    ledger = read_json(assets_dir / "ledger.json")
    usable, rejected = [], []
    listed = set()
    for a in ledger.get("assets", []):
        listed.add(a["file"])
        a = dict(a, path=str(assets_dir / a["file"]))
        if not Path(a["path"]).exists():
            rejected.append(dict(a, problems=["file not found"]))
            continue
        probs = check_entry(a)
        (rejected if probs else usable).append(dict(a, problems=probs) if probs else a)
    media = {".jpg", ".jpeg", ".png", ".webp", ".mp4", ".mov", ".mkv", ".wav", ".mp3", ".flac"}
    unlisted = [p.name for p in assets_dir.iterdir() if p.suffix.lower() in media and p.name not in listed]
    return {"usable": usable, "rejected": rejected, "unlisted": unlisted}


def credits(used_assets):
    lines = []
    for a in used_assets:
        lic = a.get("license", "")
        if lic.startswith(NEEDS_CREDIT) or lic in ("public-domain", "gov-permitted", "licensed-stock"):
            who = a.get("author") or "Unknown author"
            lines.append(f"- {a.get('title') or a['file']}: {who}, {lic}, {a.get('source', '')}")
    return lines
